name: gapsbi_env

channels:
  - conda-forge

dependencies:
  - python=3.11

  # Core scientific stack
  - numpy
  - scipy
  - h5py

  # Plotting / inspection
  - matplotlib

  # Development / testing
  - pytest

  # Nice utilities
  - tqdm
  - pyyaml
  - rich

  # Pip
  - pip